spring:
  application:
    name: cj-ai-agent
  ai:
    dashscope:
      api-key: sk-b631987d769f429fb5efc54c7960513f
      chat:
        options:
          model: qwen-plus
          bailen-knowledge-base-id: v2z32g9201
        rag:
          index-name: 情感大师
          enabled: true
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000

  datasource:
    url: jdbc:postgresql://rm-cn-c384pyl5t0001igo.rwlb.rds.aliyuncs.com:5432/cj_ai_agent
    username: my_user
    password: CJcj2020