spring:
  application:
    name: cj-ai-agent
  ai:
    dashscope:
      api-key: sk-b631987d769f429fb5efc54c7960513f
      chat:
        options:
          model: qwen-plus
          bailen-knowledge-base-id: v2z32g9201
        rag:
          index-name: 情感大师
          enabled: true
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
    mcp:
      client:
        enabled: true
        request-timeout: 30s
        stdio: #JSON目前仅支持stdio这种连接方式
          servers-configuration: classpath:mcp-servers.json #stdio本地服务端配置
      #实现远程连接
      sse:
        connections:
          server1:
            url: http://localhost:8127

  datasource:
    url: jdbc:postgresql://rm-cn-c384pyl5t0001igo.rwlb.rds.aliyuncs.com:5432/cj_ai_agent
    username: my_user
    password: CJcj2020
#search API
search-api:
  api-key: 5SinAe2iVySZJJxt3tumUbnc
